# Generated by Django 5.1.4 on 2025-01-03 21:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentslot',
            name='id',
            field=models.CharField(default=uuid.UUID('54e70761-2fc3-4264-aa31-6899a019cadf'), max_length=50, primary_key=True, serialize=False),
        ),
    ]
