# Generated by Django 5.1.4 on 2025-01-03 21:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default=uuid.UUID('8b592741-4973-4c5e-bff9-0c29f1261f61'), max_length=50, primary_key=True, serialize=False),
        ),
    ]
