# Generated by Django 5.1.4 on 2025-01-03 21:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default=uuid.UUID('d602f6ce-4806-4c37-9d0e-59288722156b'), max_length=50, primary_key=True, serialize=False),
        ),
    ]
