# Generated by Django 5.1.4 on 2025-01-03 22:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default=uuid.UUID('783dcf56-7e24-4d84-8a1b-87a80ce3f270'), max_length=50, primary_key=True, serialize=False),
        ),
    ]
